---
- hosts: v1
  pre_tasks:

    - set_fact:
        TI_HOST_CONF: []

    - include_vars: vars/prod.yml

    - set_fact:
        TI_HOST_CONF: "{{TI_HOST_CONF}} +[ TI_HOST_CONF_tmp ]"

    - include_vars: vars/rec.yml

    - set_fact:
        TI_HOST_CONF: "{{TI_HOST_CONF}} +[ TI_HOST_CONF_tmp ]"
  roles:
    # - role: provisioner
    - role: ti.generator
...
