import sys
import os
import argparse
from string import Template
import pandas as pd
from src.extract import Extract_content


# Template variables:
#   - target_file
#   - asser_options
#   - file_name
#   - iterator
#   - user
#   - group
#   - mode
TI_TEMPLATE_FUNCTION = Template("""
# target: $target_file
# assert on: $asser_options
def $func_name(host):
    file_target = host.file('$target_file')
    assert file_target.user == '$user'
    assert file_target.group == '$group'
    assert file_target.mode == 0o$mode

""")

TI_TEMPLATE_PORT_FUNCTION = Template("""
# assert on: $asser_options
def $func_name(host):
    assert host.socket("tcp://$port_address").is_listening

""")

TI_TEMPLATE_HEADER = Template("""
#######################################
# TestInfra generated by Ti-generator #
#######################################
# This tool is an open-source project on Github (https://github.com/kuty22/TI_Generator)

""")

class IT_generator_file:

    def __init__(self, content, conf):
        self.__content = content
        self.__directory = conf["directory"]
        self.__file = conf["file"]
        self.__export = list(conf["export"])

        self.__templated_files = ""
        if conf["type"] == "permissions":
            pass
        elif conf["type"] == "port":
            self.__file = self.__file.replace(".py", "-port.py")
            pass
        if self.__directory[-1] != '/':
            self.__directory = "{}/".format(self.__directory)
        tmp_path = self.__directory + self.__file
        self.__path_file = tmp_path.replace("//", "/")

        self.__create_directory()
        self.__create_file()


    def __create_directory(self):
        if os.path.isdir(self.__directory) is False:
            os.makedirs(self.__directory)

    def __create_file(self):
        if os.path.isfile(self.__path_file) is False:
            open(self.__path_file, 'a').close()

    def __check_function_name_validity(self, prefix="",sufix=""):
        file_name_for_function = self.__file.split(".")[0].replace("-","_")
        function_name = ""
        for i in range(0, 10000):
            function_name = prefix + file_name_for_function + str(i) + sufix
            if function_name not in self.__templated_files:
                break
        return function_name

    def __generate_export(self, data):
        if "csv=True" in self.__export or "csv=true" in self.__export:
            pd.DataFrame(data).to_csv(self.__path_file.replace(".py", ".csv"))
        if "xls=True" in self.__export or "xls=true" in self.__export:
            pd.DataFrame(data).to_excel(self.__path_file.replace(".py", ".xls"))

    def generate_port(self):
        file_object = open(self.__path_file, 'r')
        self.__templated_files += file_object.read()

        with open(self.__path_file,'w+') as script_template:
            # write header
            header_script = TI_TEMPLATE_HEADER.safe_substitute() if len(self.__templated_files) is 0 else ""
            script_template.write(header_script)

            tmp_tab  = []

            for configuration in self.__content:
                function_name = self.__check_function_name_validity(sufix="_port")
                self.__templated_files += TI_TEMPLATE_PORT_FUNCTION.substitute(
                    asser_options   = "['file_exist', 'user', 'group', mode]",
                    func_name       = function_name,
                    port_address    = configuration["address_port"]
                )
                tmp_tab.append(dict({
                    'func_name'       : function_name,
                    'user'            : configuration["users"],
                    'address_port'    : configuration["address_port"]
                }))

            self.__generate_export(tmp_tab)
            script_template.write(self.__templated_files)

    def generate(self):

        file_object = open(self.__path_file, 'r')
        self.__templated_files += file_object.read()

        with open(self.__path_file,'w+') as script_template:

            # write header
            header_script = TI_TEMPLATE_HEADER.safe_substitute() if len(self.__templated_files) is 0 else ""
            script_template.write(header_script)

            tmp_csv  = []

            for configuration in self.__content:
                function_name = self.__check_function_name_validity()
                self.__templated_files += TI_TEMPLATE_FUNCTION.substitute(
                    target_file     = configuration["path"],
                    asser_options   = "['file_exist', 'user', 'group', mode]",
                    func_name       = function_name,
                    user            = configuration["owner"],
                    group           = configuration["group"],
                    mode            = configuration["permissions"]["full"]
                )
                tmp_csv.append(dict({
                    'target_file'     : configuration["path"],
                    'func_name'       : function_name,
                    'user'            : configuration["owner"],
                    'group'           : configuration["group"],
                    'mode'            : configuration["permissions"]["full"]
                }))

            self.__generate_export(tmp_csv)
            script_template.write(self.__templated_files)
